@api = http://localhost:5000/api/v1

### GET monitors
GET {{api}}/monitor

### GET monitor
GET {{api}}/monitor/google-Http

### GET invalid monitor
GET {{api}}/monitor/google-Http

### DELETE monitor
DELETE {{api}}/monitor/google-Http

### GET alerts
GET {{api}}/alert

### GET alerts
GET {{api}}/alert/slack-Slack