version: '3.4'
services:
    prometheus:
        image: prom/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        ports:
            - "9090:9090"
        volumes:
            - "./prometheus.yml:/etc/prometheus/prometheus.yml"
            - "prometheus:/prometheus"
        restart: always
        networks:
            - monitoring

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000" 
        volumes:
            - "grafana:/etc/grafana"
            - "grafana_log:/var/log/grafana"
        restart: always
        networks:
            - monitoring

volumes:
    grafana: {}
    grafana_log: {}
    prometheus: {}

networks:
    monitoring: