apiVersion: v1
data:
  appsettings.json: |-
    {
        "Monitors": [
            {
                "Type": "Http",
                "Url": "https://google.com",
                "ExpectedStatusCode": 200,
                "CheckInterval": "10"
            },
            {
                "Type": "Http",
                "Url": "https://wp.pl",
                "ExpectedStatusCode": 200,
                "CheckInterval": "10"
            },
            {
                "Type": "Http",
                "Url": "https://onet.pl",
                "ExpectedStatusCode": 200,
                "CheckInterval": "10"
            },
            {
                "Type": "Http",
                "Url": "https://helion.pl",
                "ExpectedStatusCode": 200,
                "CheckInterval": "10"
            },
            {
                "Type": "Http",
                "Url": "https://jetbrains.com",
                "ExpectedStatusCode": 200,
                "CheckInterval": "10"
            },
            {
                "Type": "Http",
                "Url": "https://flyrlabs.com",
                "ExpectedStatusCode": 200,
                "CheckInterval": "10"
            },
            {
                "Type": "Http",
                "Url": "https://abb.com",
                "ExpectedStatusCode": 200,
                "CheckInterval": "10"
            },
            {
                "Type": "Http",
                "Url": "https://ubs.com",
                "ExpectedStatusCode": 200,
                "CheckInterval": "10"
            },
            {
                "Type": "Http",
                "Url": "https://interia.pl",
                "ExpectedStatusCode": 200,
                "CheckInterval": "10"
            },
            {
                "Type": "DNS",
                "Hostname": "google.com",
                "CheckInterval": "30"
            },
            {
                "Type": "DNS",
                "Hostname": "wp.pl",
                "CheckInterval": "30"
            },
            {
                "Type": "DNS",
                "Hostname": "onet.pl",
                "CheckInterval": "30"
            },
            {
                "Type": "DNS",
                "Hostname": "helion.pl",
                "CheckInterval": "30"
            },
            {
                "Type": "DNS",
                "Hostname": "jetbrains.com",
                "CheckInterval": "30"
            },
            {
                "Type": "DNS",
                "Hostname": "flyrlabs.com",
                "CheckInterval": "30"
            },
            {
                "Type": "DNS",
                "Hostname": "abb.com",
                "CheckInterval": "30"
            },
            {
                "Type": "DNS",
                "Hostname": "ubs.com",
                "CheckInterval": "30"
            },
            {
                "Type": "DNS",
                "Hostname": "interia.pl",
                "CheckInterval": "30"
            }
        ],
        "Alerts": [
            {
                "Type": "Slack",
                "SlackChannel": "#akka",
                "SlackUrl": "https://hooks.slack.com/services/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"
            }
        ]
    }
kind: ConfigMap
metadata:
  labels:
    app: akka-monitor
  namespace: monitoring
  name: appsettings-v001
